apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora02
  namespace: default
  labels:
    app: fedora02
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: fedora02
        namespace: default
      spec:
        pvc:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 30Gi
          volumeMode: Filesystem
        source:
          pvc:
            name: fedora-registry
            namespace: default
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: fedora02
        special: fedora02
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
          - name: rootdisk
            disk:
              bus: virtio
          - name: cloudinitdisk
            disk:
              bus: virtio
          interfaces:
          - masquerade: {}
            name: default
          rng: {}
        resources:
          requests:
            memory: 1Gi
      evictionStrategy: LiveMigrate
      hostname: fedora02
      networks:
      - name: default
        pod: {}
      volumes:
        - dataVolume:
            name: fedora02
          name: rootdisk
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              password: fedora
              chpasswd: { expire: False }
              ssh_pwauth: True